name: greet
on: pull_request
permissions:
  contents: read
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Print PR title
        env:
          TITLE: ${{ github.event.pull_request.title }}
        run: echo "$TITLE"
